name: standalone
description: A simple package to force the user to install pwa on mobile or browser
version: 1.0.0
homepage: https://github.com/bahiraei/standalone

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
